name: Build + Release Wheels

on:
  workflow_dispatch:
    inputs:
      use_qemu:
        description: "Use qemu for builds with targets requiring emulation"
        required: true
        default: true
      llvm_version:
        description: "LLVM version to build"
        required: false
        default: ""
      wheel_version:
        description: "Version of the wheel packaging (appended to LLVM version)"
        required: false
        default: "0"
      deploy_to_testpypi:
        description: "Whether the build should be deployed to test.pypi.org instead regular PyPI"
        required: true
        default: false

env:
  USE_QEMU: ${{ github.event.inputs.use_qemu == 'true' }}

jobs:
  build-wheels:
    strategy:
      matrix:
        arch: ["aarch64", "ppc64le", "s390x"]
        skip: ["manylinux", "musllinux"]
        include:
          - os: ubuntu-20.04
            use_qemu: true
          - os: ubuntu-20.04
            arch: "x86_64"
            use_qemu: false
          - os: ubuntu-20.04
            arch: "i686"
            use_qemu: false
          - os: windows-2019
            arch: "AMD64"
            use_qemu: false
          - os: windows-2019
            arch: "x86"
            use_qemu: false
          - os: macos-10.15
            arch: "x86_64"
            use_qemu: false
          - os: macos-10.15
            arch: "arm64"
            use_qemu: false
    name: "Build wheels on ${{ matrix.os }} (arch=${{ matrix.arch }}, skip=${{ matrix.skip }}, use_qemu=${{ matrix.use_qemu }})"
    runs-on: matrix.os

    steps:
    - uses: actions/checkout@v3
      #if: (!matrix.use_qemu) || fromJSON(env.USE_QEMU)
